/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-26 05:26:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Mariadb.imote;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public final class board_005fmodify1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.naming.InitialContext");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("javax.sql.DataSource");
    _jspx_imports_classes.add("javax.naming.Context");
    _jspx_imports_classes.add("javax.naming.NamingException");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding( "utf-8" );

	String seq = request.getParameter( "seq" );
	//System.out.println( seq );
	
	String subject = "";
	String writer = "";
	String[] mail = null;
	String content = "";
	String emot = "";
	
	Connection conn = null;
	PreparedStatement pstmt = null;
	ResultSet rs = null;
	
	try {
		Context initCtx = new InitialContext();
		Context envCtx = (Context)initCtx.lookup( "java:comp/env" );
		DataSource dataSource = (DataSource)envCtx.lookup( "jdbc/mariadb3" );
		
		conn = dataSource.getConnection();
		
		String sql = "SELECT subject, writer, mail, content, emot FROM board1 WHERE seq=?";
		pstmt = conn.prepareStatement( sql );
		pstmt.setString( 1, seq );
		
		rs = pstmt.executeQuery();
		
		if( rs.next() ) {
			subject = rs.getString( "subject" );
			writer = rs.getString( "writer" );
			emot = rs.getString("emot");

			if( rs.getString("mail").equals("") ) {
				mail = new String[] { "", "" };	
			} else {
				mail = rs.getString( "mail" ).split( "@" );
			}

			content = rs.getString( "content" );
		}
		
	} catch( NamingException e ) {
		System.out.println( "[에러] " + e.getMessage() );
	} catch( SQLException e ) {
		System.out.println( "[에러] " + e.getMessage() );
	} finally {
		if( rs != null ) rs.close();
		if( pstmt != null ) pstmt.close();
		if( conn != null ) conn.close();
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/board.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	window.onload = function() {\r\n");
      out.write("		document.getElementById( 'mbtn' ).onclick = function() {\r\n");
      out.write("			if( document.mfrm.subject.value.trim() == '' ) {\r\n");
      out.write("				alert( '제목을 입력하셔야 합니다.' );\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if( document.mfrm.password.value.trim() == '' ) {\r\n");
      out.write("				alert( '비밀번호를 입력하셔야 합니다.' );\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			document.mfrm.submit();			\r\n");
      out.write("		};\r\n");
      out.write("	};\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 상단 디자인 -->\r\n");
      out.write("<div class=\"con_title\">\r\n");
      out.write("	<h3>게시판</h3>\r\n");
      out.write("	<p>HOME &gt; 게시판 &gt; <strong>게시판</strong></p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"con_txt\">\r\n");
      out.write("	<form action=\"board_modify1_ok.jsp\" method=\"post\" name=\"mfrm\">\r\n");
      out.write("	<input type=\"hidden\" name=\"seq\" value=\"");
      out.print(seq );
      out.write("\" />\r\n");
      out.write("		<div class=\"contents_sub\">	\r\n");
      out.write("			<!--게시판-->\r\n");
      out.write("			<div class=\"board_write\">\r\n");
      out.write("				<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"top\">글쓴이</th>\r\n");
      out.write("					<td class=\"top\"><input type=\"text\" name=\"writer\" value=\"");
      out.print(writer );
      out.write("\" class=\"board_view_input_mail\" maxlength=\"5\" readonly/></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>제목</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"subject\" value=\"");
      out.print(subject );
      out.write("\" class=\"board_view_input\" /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>비밀번호</th>\r\n");
      out.write("					<td><input type=\"password\" name=\"password\" value=\"\" class=\"board_view_input_mail\"/></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>내용</th>\r\n");
      out.write("					<td><textarea name=\"content\" class=\"board_editor_area\">");
      out.print(content );
      out.write("</textarea></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이메일</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"mail1\" value=\"");
      out.print(mail[0] );
      out.write("\" class=\"board_view_input_mail\"/> @ <input type=\"text\" name=\"mail2\" value=\"");
      out.print(mail[1] );
      out.write("\" class=\"board_view_input_mail\"/></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이모티콘</th>\r\n");
      out.write("					<td align=\"center\">\r\n");
      out.write("						<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot01.png\" width=\"25\"/><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot01\" class=\"input_radio\" ");
      out.print(emot.equals("01") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot02.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot02\" class=\"input_radio\" ");
      out.print(emot.equals("02") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot03.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot03\" class=\"input_radio\" ");
      out.print(emot.equals("03") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot04.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot04\" class=\"input_radio\" ");
      out.print(emot.equals("04") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot05.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot05\" class=\"input_radio\" ");
      out.print(emot.equals("05") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot06.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot06\" class=\"input_radio\" ");
      out.print(emot.equals("06") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot07.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot07\" class=\"input_radio\" ");
      out.print(emot.equals("07") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot08.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot08\" class=\"input_radio\" ");
      out.print(emot.equals("08") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot09.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot09\" class=\"input_radio\" ");
      out.print(emot.equals("09") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot10.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot10\" class=\"input_radio\" ");
      out.print(emot.equals("10") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot11.png\" width=\"25\"/><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot11\" class=\"input_radio\" ");
      out.print(emot.equals("11") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot12.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot12\" class=\"input_radio\" ");
      out.print(emot.equals("12") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot13.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot13\" class=\"input_radio\" ");
      out.print(emot.equals("13") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot14.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot14\" class=\"input_radio\" ");
      out.print(emot.equals("14") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot15.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot15\" class=\"input_radio\" ");
      out.print(emot.equals("15") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot16.png\" width=\"25\"/><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot16\" class=\"input_radio\" ");
      out.print(emot.equals("16") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot17.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot17\" class=\"input_radio\" ");
      out.print(emot.equals("17") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot18.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot18\" class=\"input_radio\" ");
      out.print(emot.equals("18") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot19.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot19\" class=\"input_radio\" ");
      out.print(emot.equals("19") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot20.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot20\" class=\"input_radio\" ");
      out.print(emot.equals("20") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot21.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot21\" class=\"input_radio\" ");
      out.print(emot.equals("21") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot22.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot22\" class=\"input_radio\" ");
      out.print(emot.equals("22") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot23.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot23\" class=\"input_radio\" ");
      out.print(emot.equals("23") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot24.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot24\" class=\"input_radio\" ");
      out.print(emot.equals("24") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot25.png\" width=\"25\"/><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot25\" class=\"input_radio\" ");
      out.print(emot.equals("25") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot26.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot26\" class=\"input_radio\" ");
      out.print(emot.equals("26") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot27.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot27\" class=\"input_radio\" ");
      out.print(emot.equals("27") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot28.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot28\" class=\"input_radio\" ");
      out.print(emot.equals("28") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot29.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot29\" class=\"input_radio\" ");
      out.print(emot.equals("29") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot30.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot30\" class=\"input_radio\" ");
      out.print(emot.equals("30") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot31.png\" width=\"25\"/><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot31\" class=\"input_radio\" ");
      out.print(emot.equals("31") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot32.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot32\" class=\"input_radio\" ");
      out.print(emot.equals("32") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot33.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot33\" class=\"input_radio\" ");
      out.print(emot.equals("33") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot34.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot34\" class=\"input_radio\" ");
      out.print(emot.equals("34") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot35.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot35\" class=\"input_radio\" ");
      out.print(emot.equals("35") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot36.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot36\" class=\"input_radio\" ");
      out.print(emot.equals("36") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot37.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot37\" class=\"input_radio\" ");
      out.print(emot.equals("37") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot38.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot38\" class=\"input_radio\" ");
      out.print(emot.equals("38") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot39.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot39\" class=\"input_radio\" ");
      out.print(emot.equals("39") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot40.png\" width=\"25\"/><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot40\" class=\"input_radio\" ");
      out.print(emot.equals("40") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot41.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot41\" class=\"input_radio\" ");
      out.print(emot.equals("41") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot42.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot42\" class=\"input_radio\" ");
      out.print(emot.equals("42") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot43.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot43\" class=\"input_radio\" ");
      out.print(emot.equals("43") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot44.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot44\" class=\"input_radio\" ");
      out.print(emot.equals("44") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<img src=\"../../images/emoticon/emot45.png\" width=\"25\" /><br />\r\n");
      out.write("								<input type=\"radio\" name=\"emot\" value=\"emot45\" class=\"input_radio\" ");
      out.print(emot.equals("45") ? "checked='checked'" : "" );
      out.write("/>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"btn_area\">\r\n");
      out.write("				<div class=\"align_left\">\r\n");
      out.write("					<input type=\"button\" value=\"목록\" class=\"btn_list btn_txt02\" style=\"cursor: pointer;\" onclick=\"location.href='board_list1.jsp'\" />\r\n");
      out.write("					<input type=\"button\" value=\"보기\" class=\"btn_list btn_txt02\" style=\"cursor: pointer;\" onclick=\"location.href='board_view1.jsp'\" />\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"align_right\">\r\n");
      out.write("					<input type=\"button\" id=\"mbtn\" value=\"수정\" class=\"btn_write btn_txt01\" style=\"cursor: pointer;\" />\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--//게시판-->\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 하단 디자인 -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
